### ISSUE TITLE
ble_app_uart_adc_battery_measurement example

### ISSUE THREAD

**Issue by SoniaZotz** [NordicPlayground/nrf51-ADC-examples#5]
Does not compile cleanly 

nRF5_SDK_12.3.0_d7731ad\examples\ble_peripheral\ble_app_hrs_adc_battery_measurement\pca10028\s130\arm5_no_packs

compiling main.c...
..\..\..\main.c(1017): warning:  #177-D: function "uart_init"  was declared but never referenced
  static void uart_init(void)
..\..\..\main.c(1087): warning:  #177-D: function "adc_config"  was declared but never referenced
  static void adc_config(void)
..\..\..\main.c: 2 warnings, 0 errors

linking...
.\_build\nrf51422_xxac.axf: Error: L6218E: Undefined symbol app_sched_event_put (referred from main.o).
.\_build\nrf51422_xxac.axf: Error: L6218E: Undefined symbol nrf_drv_adc_buffer_convert (referred from main.o).
.\_build\nrf51422_xxac.axf: Error: L6218E: Undefined symbol nrf_drv_adc_sample (referred from main.o).

**Comment by jorhol** [comment]
Fixed issues in projects.
